apiVersion: apps/v1
kind: Deployment
metadata:
name: nagp-devops-home-assignment-2022
labels:
  app: nagp-devops-home-assignment-2022
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: nagp-devops-home-assignment-2022
      tier: nagp-devops-home-assignment-2022
  spec:
    containers:
    - name: hello
      image: khatridarshan16/i-khatridarshan16-develop:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: nagp-devops-home-assignment-2022

---
apiVersion: v1
kind: Service
metadata:
name: nagp-devops-home-assignment-2022
labels:
  app: nagp-devops-home-assignment-2022
spec:
ports:
  - port: 3000
    targetPort: 3000
selector:
  app: nagp-devops-home-assignment-2022
  tier: nagp-devops-home-assignment-2022
type: LoadBalancer

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-cluster-khatribhavikbhai
  labels:
    name: kubernetes-cluster-khatribhavikbhai
